# Generated by Django 4.1 on 2022-08-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_location_id_user_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='location_id',
            field=models.ManyToManyField(to='users.location'),
        ),
    ]
