# Generated by Django 4.1 on 2022-08-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.IntegerField(),
        ),
    ]
