# Generated by Django 4.1 on 2022-08-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_rename_author_ad_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
