# Generated by Django 4.1 on 2022-08-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_ad_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='author',
            new_name='author_id',
        ),
    ]
