# Generated by Django 4.1 on 2022-09-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_alter_ad_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='author_id',
            new_name='author_id_id',
        ),
    ]
