# Generated by Django 4.1 on 2022-09-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_rename_author_id_ad_author_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='author_id_id',
            new_name='author_id',
        ),
    ]
