# Generated by Django 4.1 on 2022-09-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_alter_ad_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='category_id',
            new_name='category',
        ),
    ]
